# Generated by Django 2.2.4 on 2019-08-13 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessdefinition_q', models.CharField(max_length=200)),
                ('businessdefinition_a', models.TextField()),
                ('jurisdiction', models.CharField(max_length=200)),
                ('businessdefinition', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Controls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FinalTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regulation', models.CharField(max_length=50)),
                ('businessdefinition_a', models.TextField()),
                ('process', models.CharField(max_length=50)),
                ('controlarea', models.CharField(max_length=50)),
                ('risk', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Regulations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regulation', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk', models.CharField(max_length=50)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RiskReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regulation', models.CharField(max_length=50)),
                ('businessdefinition_q', models.CharField(max_length=200)),
                ('businessdefinition_a', models.TextField()),
                ('jurisdiction', models.CharField(max_length=200)),
                ('process', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('controlarea', models.CharField(max_length=50)),
                ('controlobjective', models.TextField()),
                ('controldescription', models.TextField()),
                ('status', models.CharField(default='pending', max_length=50)),
                ('edit_status', models.CharField(default='pending', max_length=10)),
                ('risk', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regulation', models.CharField(max_length=50)),
                ('businessdefinition_q', models.CharField(max_length=200)),
                ('businessdefinition_a', models.TextField()),
                ('jurisdiction', models.CharField(max_length=200)),
                ('process', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(default='pending', max_length=50)),
                ('edit_status', models.CharField(default='pending', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ControlReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regulation', models.CharField(max_length=50)),
                ('businessdefinition_q', models.CharField(max_length=200)),
                ('businessdefinition_a', models.TextField()),
                ('jurisdiction', models.CharField(max_length=200)),
                ('process', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('controlarea', models.CharField(max_length=50)),
                ('controlobjective', models.TextField()),
                ('controldescription', models.TextField()),
                ('status', models.CharField(default='pending', max_length=50)),
                ('edit_status', models.CharField(default='pending', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BAReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regulation', models.CharField(max_length=50)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('edit_status', models.CharField(default='pending', max_length=10)),
                ('businessdefinition_q', models.CharField(max_length=200)),
                ('businessdefinition_a', models.TextField()),
                ('jurisdiction', models.CharField(max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
