# Generated by Django 2.1.10 on 2019-08-14 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DJ', '0004_business'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='businessActivity',
            new_name='businessactivity',
        ),
    ]
