# Generated by Django 2.1.10 on 2019-08-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DJ', '0005_auto_20190814_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='edit_status',
            field=models.CharField(default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='business',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
