# Generated by Django 2.2.3 on 2019-08-21 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DJ', '0007_auto_20190819_1114'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Maptable',
        ),
    ]
