# Generated by Django 2.1.10 on 2019-08-23 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DJ', '0008_delete_maptable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessactivity',
            name='created_at',
        ),
    ]
