# Generated by Django 2.1.10 on 2019-08-23 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DJ', '0009_remove_businessactivity_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regulations',
            name='created_at',
        ),
    ]
