# Generated by Django 2.1.12 on 2019-09-18 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DJ', '0011_auto_20190918_1528'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Controls',
        ),
    ]
