# Generated by Django 2.2.3 on 2019-09-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DJ', '0015_auto_20190918_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='bareg',
            name='category',
            field=models.CharField(default='Individual', max_length=100),
        ),
        migrations.AddField(
            model_name='business',
            name='category',
            field=models.CharField(default='Individual', max_length=100),
        ),
        migrations.AddField(
            model_name='businessactivity',
            name='category',
            field=models.CharField(default='Individual', max_length=100),
        ),
        migrations.AddField(
            model_name='controlreg',
            name='category',
            field=models.CharField(default='Individual', max_length=100),
        ),
        migrations.AddField(
            model_name='controls',
            name='category',
            field=models.CharField(default='Individual', max_length=100),
        ),
        migrations.AddField(
            model_name='policy',
            name='category',
            field=models.CharField(default='Individual', max_length=100),
        ),
        migrations.AddField(
            model_name='processreg',
            name='category',
            field=models.CharField(default='Individual', max_length=100),
        ),
        migrations.AddField(
            model_name='regulations',
            name='category',
            field=models.CharField(default='Individual', max_length=100),
        ),
        migrations.AddField(
            model_name='risk',
            name='category',
            field=models.CharField(default='Individual', max_length=100),
        ),
        migrations.AddField(
            model_name='riskreg',
            name='category',
            field=models.CharField(default='Individual', max_length=100),
        ),
    ]
