# Generated by Django 2.2.3 on 2019-09-20 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DJ', '0016_auto_20190920_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='category',
        ),
        migrations.RemoveField(
            model_name='controls',
            name='category',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='category',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='category',
        ),
    ]
