# Generated by Django 2.1.12 on 2019-09-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DJ', '0017_auto_20190920_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessactivity',
            name='category',
        ),
        migrations.RemoveField(
            model_name='regulations',
            name='category',
        ),
        migrations.AddField(
            model_name='riskreg',
            name='riskdescription',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='bareg',
            name='category',
            field=models.CharField(default='Individual', max_length=255),
        ),
        migrations.AlterField(
            model_name='bareg',
            name='edit_status',
            field=models.CharField(default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='bareg',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='business',
            name='edit_status',
            field=models.CharField(default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='business',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='controlreg',
            name='category',
            field=models.CharField(default='Individual', max_length=255),
        ),
        migrations.AlterField(
            model_name='controlreg',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='processreg',
            name='category',
            field=models.CharField(default='Individual', max_length=255),
        ),
        migrations.AlterField(
            model_name='processreg',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='riskreg',
            name='category',
            field=models.CharField(default='Individual', max_length=255),
        ),
        migrations.AlterField(
            model_name='riskreg',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
