# Generated by Django 2.1.12 on 2019-09-26 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DJ', '0019_auto_20190926_1812'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BusinessGroups',
            new_name='BusinessGroup',
        ),
    ]
