# Generated by Django 2.1.12 on 2019-09-26 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DJ', '0021_businessgroup_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessgroup',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
